### ISSUE TITLE
Create examples directory and adding whois example code

### ISSUE THREAD

**Issue by tjyang** [sunfmin/fanout#1]
Can I trouble you to add the whois example you posted on ggroup into an examples directory ? We can collect many more examples of using your packages later on.

**Comment by sunfmin** [comment]
The code is at https://github.com/sunfmin/domaincheck, Do you think it needs to put into the same repository?

**Comment by sunfmin** [comment]
I could add a list of project who used the package if they let me know later on. :-), But thanks.

**Comment by tjyang** [comment]
I was hoping there is a examples directory can be created  in fanout top directory. Thanks for considering.
