### ISSUE TITLE
the domaincheck can not work in centos7.2

### ISSUE THREAD

**Issue by liuts** [sunfmin/fanout#10]
https://github.com/sunfmin/domaincheck/blob/master/main.go

Error:  exit status 1
exit status 1
Error:  exit status 1
exit status 1
Error:  exit status 1
exit status 1
Error:  exit status 1

**Comment by sunfmin** [comment]
应该是这里出了问题
```
	cmd := exec.Command("whois", domain)
```
不知道有没有不用调用命令行，而是调用包里方法的方式来查询域名的有没有占用。你研究一下？
